# Generated by Django 4.2.4 on 2024-12-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forummodel',
            name='ForumImage',
            field=models.ImageField(blank=True, default='board_images/bootstrap.png', null=True, upload_to='board_images/'),
        ),
    ]
